//package std_mngt; /*
package requiredFunctions;

// package com.mycompany.mavenproject1;
//import std_mngt.Gui;
import java.awt.*;
import java.awt.print.*;
import javax.swing.*;

/**
 * @author anurag
 */
@SuppressWarnings("serial")
public class panelPrint extends javax.swing.JFrame {

    /**
     * Creates new form panelPrint
     */
    public panelPrint() {
        initComponents();
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//    setSize(new Dimension(1020,1720));
    }

    public void fillForm(
            String enrollment,
            String fullname,
            String gender,
            String DOB,
            String fatherName,
            String aadhar,
            String catergory,
            String branch,
            String batch,
            String marks10,
            String mobile,
            String email,
            String address,
            String dateTime) {

        setEnrollment.setText(enrollment);
        setFatherName.setText(fatherName);
        setFullname.setText(fullname);
        setGender.setText(gender);
        setDOB.setText(DOB);
        setAadhar.setText(aadhar);
        setCatergory.setText(catergory);
        setBatch.setText(batch);
        setBranch.setText(branch);
        setEmail.setText(email);
        setmarks10.setText(marks10);
        setMobile.setText(mobile);
        setAddress.setText(address);
        setDateTime.setText(dateTime);
    }

    public void printPanel() {
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                pf.setOrientation(PageFormat.PORTRAIT);
                System.out.println(pf.getHeight());
                System.out.println(pf.getWidth());
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47, 0.47);

                printPanek.print(g2);

                return Printable.PAGE_EXISTS;

            }
        });
        boolean ok = job.printDialog();
        if (ok) {
            try {

                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        printPanek = new javax.swing.JPanel();
        titleLB = new javax.swing.JLabel();
        titleLB1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        setEnrollment = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titleLB2 = new javax.swing.JLabel();
        titleLB3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        setFullname = new javax.swing.JLabel();
        setDOB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        setDOB1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        setGender = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        setFatherName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        setAadhar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        setCatergory = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        setBranch = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        setBatch = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        setmarks10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        setMobile = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        setEmail = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        setAddress = new javax.swing.JLabel();
        setDateTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        printPanek.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
//    setMinimumSize(new java.awt.Dimension(1220, 1130));
//    setPreferredSize(new java.awt.Dimension(1220, 1130));
//    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JScrollPane jScrollPane1 = new JScrollPane();
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

//    printPanek.setBackground(new java.awt.Color(204, 204, 255));
        printPanek.setPreferredSize(new java.awt.Dimension(1305, 1700));
//    printPanek.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        //        titleLB.setBackground(#991f17);
        titleLB.setFont(new java.awt.Font("FiraCode Nerd Font SemBd", 0, 28)); // NOI18N
        titleLB.setForeground(new java.awt.Color(232, 16, 11));
        titleLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLB.setIcon(
                new javax.swing.ImageIcon(
                        "D:\\Serious Project\\trailTwo\\trailTwoc\\src\\std_mngt\\icons\\gpc_logo.jpeg")); // NOI18N
        titleLB.setText("Govt. PolyTechnic College Sironj");
        titleLB.setBorder(
                javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(0, 0, 0)));
        titleLB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        titleLB.setIconTextGap(50);

        //        titleLB1.setBackground(#991f17);
        titleLB1.setFont(new java.awt.Font("FiraCode Nerd Font SemBd", 0, 14)); // NOI18N
        titleLB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLB1.setText("Lateri Road Distt Vidisha, Madhya Pradesh, PinCode 464228");
        titleLB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(254, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1427, 1700));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 9, Short.MAX_VALUE));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setText("Enrollment No.");

        setEnrollment.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setEnrollment.setText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setText("Student Name");

        //        titleLB2.setBackground(#991f17);
        titleLB2.setFont(new java.awt.Font("FiraCode Nerd Font SemBd", 0, 14)); // NOI18N
        titleLB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLB2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        //        titleLB3.setBackground(#991f17);
        titleLB3.setFont(new java.awt.Font("FiraCode Nerd Font SemBd", 0, 14)); // NOI18N
        titleLB3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLB3.setText("Affilated By AICTE & RGPV");
        titleLB3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel4.setText("Personal Detail");

        setFullname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setFullname.setText("Anurag Gupta");

        setDOB.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setDOB.setText("2005-08-29");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel5.setText("Year Of Birth");

        setDOB1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel6.setText("Gender");

        setGender.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setGender.setText("Male");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel7.setText("Father Name");

        setFatherName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setFatherName.setText("Shiv Kumar Gupta");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel8.setText("Aadhar No");

        setAadhar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setAadhar.setText("012345678912");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel9.setText("Catergory");

        setCatergory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setCatergory.setText("General");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel10.setText("Admission Info");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel11.setText("Branch");

        setBranch.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setBranch.setText("Computer Science & Engineering");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel12.setText("Batch");

        setBatch.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setBatch.setText("2021");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel13.setText("10th Marks ");

        setmarks10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setmarks10.setText("74.5");

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel14.setText("Student Contact Info");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel15.setText("Mobile No");

        setMobile.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setMobile.setText("9876543210");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel16.setText("Email ID");

        setEmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setEmail.setText("anuragsgupta9211@gmail.com");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel17.setText("Address");

        setAddress.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setAddress.setText("Royal City, Sironj Vidisha");

        setDateTime.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setDateTime.setText("Date & Time");

        javax.swing.GroupLayout printPanekLayout = new javax.swing.GroupLayout(printPanek);
        printPanek.setLayout(printPanekLayout);
        printPanekLayout.setHorizontalGroup(
                printPanekLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(
                                titleLB,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addGroup(
                                printPanekLayout
                                        .createSequentialGroup()
                                        .addGroup(
                                                printPanekLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(
                                                                jPanel2,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                1067,
                                                                Short.MAX_VALUE)
                                                        .addGroup(
                                                                printPanekLayout
                                                                        .createSequentialGroup()
                                                                        .addGroup(
                                                                                printPanekLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(
                                                                                                printPanekLayout
                                                                                                        .createSequentialGroup()
                                                                                                        .addGap(403, 403, 403)
                                                                                                        .addComponent(
                                                                                                                titleLB3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                301,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addGap(62, 62, 62)
                                                                                                        .addComponent(
                                                                                                                titleLB2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                301,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(
                                                                                                printPanekLayout
                                                                                                        .createSequentialGroup()
                                                                                                        .addGap(100, 100, 100)
                                                                                                        .addGroup(
                                                                                                                printPanekLayout
                                                                                                                        .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                        .addGroup(
                                                                                                                                printPanekLayout
                                                                                                                                        .createSequentialGroup()
                                                                                                                                        .addGroup(
                                                                                                                                                printPanekLayout
                                                                                                                                                        .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                        .addComponent(jLabel1)
                                                                                                                                                        .addComponent(jLabel3)
                                                                                                                                                        .addComponent(jLabel5)
                                                                                                                                                        .addComponent(jLabel8))
                                                                                                                                        .addGap(100, 100, 100)
                                                                                                                                        .addGroup(
                                                                                                                                                printPanekLayout
                                                                                                                                                        .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                        .addComponent(
                                                                                                                                                                setEnrollment,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                108,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                        .addGroup(
                                                                                                                                                                printPanekLayout
                                                                                                                                                                        .createSequentialGroup()
                                                                                                                                                                        .addGroup(
                                                                                                                                                                                printPanekLayout
                                                                                                                                                                                        .createParallelGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                setDOB,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                108,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                setFullname,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                187,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                setAadhar,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                108,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                setBranch))
                                                                                                                                                                        .addGap(
                                                                                                                                                                                115, 115,
                                                                                                                                                                                115)
                                                                                                                                                                        .addGroup(
                                                                                                                                                                                printPanekLayout
                                                                                                                                                                                        .createParallelGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                jLabel7)
                                                                                                                                                                                        .addGroup(
                                                                                                                                                                                                printPanekLayout
                                                                                                                                                                                                        .createSequentialGroup()
                                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                                jLabel6)
                                                                                                                                                                                                        .addGroup(
                                                                                                                                                                                                                printPanekLayout
                                                                                                                                                                                                                        .createParallelGroup(
                                                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                                        .addGroup(
                                                                                                                                                                                                                                printPanekLayout
                                                                                                                                                                                                                                        .createSequentialGroup()
                                                                                                                                                                                                                                        .addPreferredGap(
                                                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                                                                setDOB1,
                                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                                108,
                                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                                                                        .addGroup(
                                                                                                                                                                                                                                printPanekLayout
                                                                                                                                                                                                                                        .createSequentialGroup()
                                                                                                                                                                                                                                        .addGap(
                                                                                                                                                                                                                                                100,
                                                                                                                                                                                                                                                100,
                                                                                                                                                                                                                                                100)
                                                                                                                                                                                                                                        .addGroup(
                                                                                                                                                                                                                                                printPanekLayout
                                                                                                                                                                                                                                                        .createParallelGroup(
                                                                                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                                                                                setFatherName,
                                                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                                                184,
                                                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                                                                                setCatergory,
                                                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                                                108,
                                                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                                                                                setmarks10)
                                                                                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                                                                                setEmail)
                                                                                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                                                                                setGender,
                                                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                                                108,
                                                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                jLabel9)
                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                jLabel13)
                                                                                                                                                                                        .addComponent(
                                                                                                                                                                                                jLabel16)))))
                                                                                                                        .addGroup(
                                                                                                                                printPanekLayout
                                                                                                                                        .createSequentialGroup()
                                                                                                                                        .addGroup(
                                                                                                                                                printPanekLayout
                                                                                                                                                        .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                        .addComponent(jLabel11)
                                                                                                                                                        .addComponent(jLabel12))
                                                                                                                                        .addGap(158, 158, 158)
                                                                                                                                        .addGroup(
                                                                                                                                                printPanekLayout
                                                                                                                                                        .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                        .addComponent(setMobile)
                                                                                                                                                        .addComponent(setBatch)
                                                                                                                                                        .addComponent(
                                                                                                                                                                setAddress)))))
                                                                                        .addGroup(
                                                                                                printPanekLayout
                                                                                                        .createSequentialGroup()
                                                                                                        .addGap(50, 50, 50)
                                                                                                        .addComponent(
                                                                                                                jLabel4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                170,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(
                                                                                                printPanekLayout
                                                                                                        .createSequentialGroup()
                                                                                                        .addGap(50, 50, 50)
                                                                                                        .addComponent(
                                                                                                                jLabel10,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                201,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(
                                                                                                printPanekLayout
                                                                                                        .createSequentialGroup()
                                                                                                        .addGap(50, 50, 50)
                                                                                                        .addComponent(
                                                                                                                jLabel14,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                201,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(
                                                                                                printPanekLayout
                                                                                                        .createSequentialGroup()
                                                                                                        .addGap(100, 100, 100)
                                                                                                        .addGroup(
                                                                                                                printPanekLayout
                                                                                                                        .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                        .addComponent(jLabel17)
                                                                                                                        .addComponent(jLabel15))))
                                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                        .addContainerGap())
                        .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                printPanekLayout
                                        .createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(
                                                printPanekLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                printPanekLayout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                titleLB1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                523,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(237, 237, 237))
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                printPanekLayout
                                                                        .createSequentialGroup()
                                                                        .addComponent(setDateTime)
                                                                        .addGap(155, 155, 155)))));
        printPanekLayout.setVerticalGroup(
                printPanekLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                printPanekLayout
                                        .createSequentialGroup()
                                        .addComponent(titleLB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                titleLB1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                18,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(
                                                printPanekLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                printPanekLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(titleLB2))
                                                        .addGroup(
                                                                printPanekLayout
                                                                        .createSequentialGroup()
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(
                                                                                titleLB3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                18,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(
                                                jPanel2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                9,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                setDateTime,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                21,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel4)
                                        .addGap(15, 15, 15)
                                        .addGroup(
                                                printPanekLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(setEnrollment)
                                                        .addComponent(jLabel1))
                                        .addGap(27, 27, 27)
                                        .addGroup(
                                                printPanekLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(setFullname)
                                                        .addComponent(setDOB1)
                                                        .addComponent(jLabel6)
                                                        .addComponent(setGender))
                                        .addGap(27, 27, 27)
                                        .addGroup(
                                                printPanekLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(setDOB)
                                                        .addComponent(jLabel7)
                                                        .addComponent(setFatherName))
                                        .addGap(27, 27, 27)
                                        .addGroup(
                                                printPanekLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(setAadhar)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9)
                                                        .addComponent(setCatergory))
                                        .addGap(21, 21, 21)
                                        .addComponent(
                                                jLabel10,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(
                                                printPanekLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(setBranch)
                                                        .addComponent(jLabel13)
                                                        .addComponent(setmarks10))
                                        .addGap(27, 27, 27)
                                        .addGroup(
                                                printPanekLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel12)
                                                        .addComponent(setBatch))
                                        .addGap(32, 32, 32)
                                        .addComponent(
                                                jLabel14,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                printPanekLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                printPanekLayout
                                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel15)
                                                                        .addComponent(setMobile)
                                                                        .addComponent(jLabel16))
                                                        .addComponent(setEmail))
                                        .addGap(27, 27, 27)
                                        .addGroup(
                                                printPanekLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel17)
                                                        .addComponent(
                                                                setAddress,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                21,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(428, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1077, Short.MAX_VALUE)
                        .addGroup(
                                layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(
                                                layout
                                                        .createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(
                                                                printPanek,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))));
        layout.setVerticalGroup(
                layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1119, Short.MAX_VALUE)
                        .addGroup(
                                layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(
                                                layout
                                                        .createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(
                                                                printPanek,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))));

        pack();
    } // </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelPrint.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelPrint.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelPrint.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelPrint.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable() {
            public void run() {
                new panelPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel printPanek;
    private javax.swing.JLabel setAadhar;
    private javax.swing.JLabel setAddress;
    private javax.swing.JLabel setBatch;
    private javax.swing.JLabel setBranch;
    private javax.swing.JLabel setCatergory;
    private javax.swing.JLabel setDOB;
    private javax.swing.JLabel setDOB1;
    private javax.swing.JLabel setDateTime;
    private javax.swing.JLabel setEmail;
    private javax.swing.JLabel setEnrollment;
    private javax.swing.JLabel setFatherName;
    private javax.swing.JLabel setFullname;
    private javax.swing.JLabel setGender;
    private javax.swing.JLabel setMobile;
    private javax.swing.JLabel setmarks10;
    private javax.swing.JLabel titleLB;
    private javax.swing.JLabel titleLB1;
    private javax.swing.JLabel titleLB2;
    private javax.swing.JLabel titleLB3;
    // End of variables declaration
}
